language: php
 
php:
  - 7.2
  - 7.3
 
before_script:
  - composer install --prefer-source --no-interaction --no-dev
 
script: 
  - phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
